services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    networks:
      - sample-fastapi-react-network

  db:
    image: mysql:8.0
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - sample-fastapi-react-network

  test_db:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
      - test-db-data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3307:3307"
    networks:
      - sample-fastapi-react-network

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "5173:5173"
    networks:
      - sample-fastapi-react-network

volumes:
  db-data:
  test-db-data:

networks:
  sample-fastapi-react-network:
    driver: bridge
