version: "3.8"

services:
  fastapi:
    build:
      context: . # ビルドコンテキストはプロジェクトルートディレクトリ
      dockerfile: ./docker/api/Dockerfile # Dockerfileへの相対パスを指定
    ports:
      - "8000:80"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=mysql://user:password@db:3306/mydatabase
    depends_on:
      - db

  db:
    image: mysql:8.0
    platform: linux/arm64/v8 # Appleシリコン用にARMアーキテクチャを指定
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/conf.d/my.cnf:/etc/mysql/my.cnf
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"

volumes:
  mysql-data:
