services:
  fastapi:
    build:
      context: . # ビルドコンテキストはプロジェクトルートディレクトリ
      dockerfile: ./docker/api/Dockerfile # Dockerfileへの相対パスを指定
    ports:
      - "8000:80"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mysql:8.0
    platform: linux/arm64/v8 # Appleシリコン用にARMアーキテクチャを指定
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/conf.d/my.cnf:/etc/mysql/my.cnf
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    networks:
      - backend

  test_db:
    image: mysql:8.0
    platform: linux/arm64/v8 # Appleシリコン用にARMアーキテクチャを指定
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/conf.d/my.cnf:/etc/mysql/my.cnf
      - test-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3307:3307"
    networks:
      - backend

volumes:
  db-data:
  test-db-data:

networks:
  backend:
    driver: bridge
