services:
  fastapi:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mysql:8.0
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/db/conf.d/my.cnf:/etc/mysql/my.cnf
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - backend

  test_db:
    image: mysql:8.0
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/test_db/conf.d/my.cnf:/etc/mysql/my.cnf
      - test-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${TEST_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3307"
    networks:
      - backend

volumes:
  db-data:
  test-db-data:

networks:
  backend:
    driver: bridge
